config/routes.rb
Rails.application.routes.draw do
  root 'expenses#new'

  resources :expenses
  resources :categories
  resources :users
  get 'expenses-data', to: 'expenses#load'

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

end

app/views/layouts/_assets.html.erb
<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true %>
<%= stylesheet_link_tag    'toastr.css', media: 'all', 'data-turbolinks-track': true %>
<%= stylesheet_link_tag    'jquery-ui.css', media: 'all', 'data-turbolinks-track': true %>
<%= stylesheet_link_tag    'mdb/css/bootstrap', media: 'all', 'data-turbolinks-track': true %>
<%= stylesheet_link_tag    'mdb/css/mdb', media: 'all', 'data-turbolinks-track': true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': true %>
<%#= javascript_include_tag 'jquery3.js', 'data-turbolinks-track': true %>
<%= javascript_include_tag 'mdb/js/jquery-3.3.1.min', 'data-turbolinks-track': true %>
<%= javascript_include_tag 'jquery_ujs.js', 'data-turbolinks-track': true %>
<%= javascript_include_tag 'jquery-ui.js', 'data-turbolinks-track': true %>
<%#= javascript_include_tag 'popper.js', 'data-turbolinks-track': true %>
<%= javascript_include_tag 'mdb/js/popper.min', 'data-turbolinks-track': true %>
<%#= javascript_include_tag 'bootstrap.min.js', 'data-turbolinks-track': true %>
<%= javascript_include_tag 'mdb/js/bootstrap', 'data-turbolinks-track': true %>
<%= javascript_include_tag 'toastr.min.js', 'data-turbolinks-track': true %>
<%= javascript_include_tag 'bootstrap-datepicker', 'data-turbolinks-track': true %>
<%= stylesheet_link_tag    'bootstrap-datepicker3', media: 'all', 'data-turbolinks-track': true %>

app/views/layouts/_flash.html.erb
<% if flash.present? %>
  <div id='flash'>
    <script>
        <% if flash[:success] %>
        let $toastContent = $('<span><%= flash[:success] %></span>');
        toastr.success($toastContent);
        <% end %>
        <% if flash[:info] %>
        let $toastContent = $('<span><%= flash[:info] %></span>');
        toastr.info($toastContent);
        <% end %>
        <% if flash[:danger] %>
        let $toastContent = $('<span><%= flash[:danger] %></span>');
        toastr.error($toastContent);
        <% end %>
    </script>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg fixed-top">
  <%= link_to root_path do %>
    <%= image_tag 'logo-linear1.png' %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse ml-auto" id="navbarNavDropdown">

    <% if logged_in? %>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'New Expense', new_expense_path, class: 'nav-link', id: 'add-expense' %>
        </li>
        <li class="nav-item">
          <%= link_to "Expenses", expenses_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Categories", categories_path, class: 'nav-link' %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Account
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", user_path(current_user), class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to "Logout", logout_path, method: :delete, class: 'dropdown-item' %>
          </div>
        </li>
      </ul>
    <% else %>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Log in", login_path, class: 'nav-link' %>
        </li>
      </ul>
    <% end %>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyExpenses</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= render 'layouts/assets' %>
</head>

<body>
<%= render 'layouts/header' %>
<div class="container page-body">
  <%= render 'layouts/flash' %>
  <%= yield %>
</div>
<%= yield :javascript %>
</body>
</html>